-- Supabase Schema Definition for DoClimb App

-- -----------------------------------------------------------------------------
-- DROP existing tables, functions, and policies for a clean rebuild
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS public.community_posts CASCADE;
DROP TABLE IF EXISTS public.records CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- Drop handle_new_user function (if it exists)
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;


-- -----------------------------------------------------------------------------
-- Create the profiles table
-- -----------------------------------------------------------------------------
CREATE TABLE public.profiles (
  id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  name TEXT NOT NULL,           -- '이름' 역할, 필수
  display_nickname TEXT UNIQUE NOT NULL, -- '닉네임' 역할, 고유하고 필수
  email TEXT UNIQUE NOT NULL,             -- 사용자 이메일, 고유하고 필수 (로그인 시 필요)
  climbing_level TEXT,          -- 선택 정보
  preferred_gym TEXT,           -- 선택 정보
  climbing_style TEXT[] DEFAULT '{}'::TEXT[], -- 선택 정보, 배열
  avatar_url TEXT,
  website TEXT,
  role TEXT DEFAULT 'USER' NOT NULL, -- 역할, 기본값 USER
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(), -- 생성 시간
  PRIMARY KEY (id)
);

-- -----------------------------------------------------------------------------
-- Set up Row Level Security (RLS) for profiles table
-- -----------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
ON public.profiles FOR SELECT
USING (true);

CREATE POLICY "Users can insert their own profile."
ON public.profiles FOR INSERT
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile."
ON public.profiles FOR UPDATE
USING (auth.uid() = id);

CREATE POLICY "Users can delete their own profile."
ON public.profiles FOR DELETE
USING (auth.uid() = id);

-- -----------------------------------------------------------------------------
-- Function and Trigger to automatically create a profile for a new user
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, display_nickname, climbing_level, preferred_gym, climbing_style)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'name', 'New User'),
    COALESCE(new.raw_user_meta_data->>'display_nickname', 'missing_display_nickname_' || substr(new.id::text, 1, 8)),
    new.raw_user_meta_data->>'climbing_level',
    new.raw_user_meta_data->>'preferred_gym',
    (SELECT CASE
      WHEN new.raw_user_meta_data->'climbing_style' IS NOT NULL AND jsonb_typeof((new.raw_user_meta_data->'climbing_style')::jsonb) = 'array'
      THEN ARRAY(SELECT jsonb_array_elements_text((new.raw_user_meta_data->'climbing_style')::jsonb))
      ELSE '{}'::TEXT[]
    END)
  )
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    display_nickname = EXCLUDED.display_nickname,
    email = EXCLUDED.email,
    climbing_level = EXCLUDED.climbing_level,
    preferred_gym = EXCLUDED.preferred_gym,
    climbing_style = EXCLUDED.climbing_style,
    updated_at = NOW();
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- -----------------------------------------------------------------------------
-- Create the records table
-- -----------------------------------------------------------------------------
CREATE TABLE public.records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  date DATE NOT NULL,
  location TEXT,
  climb_type TEXT,
  difficulty TEXT,
  success BOOLEAN DEFAULT FALSE,
  is_public BOOLEAN DEFAULT FALSE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL
);

-- -----------------------------------------------------------------------------
-- Set up Row Level Security (RLS) for records table
-- -----------------------------------------------------------------------------
ALTER TABLE public.records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view public records or their own."
ON public.records FOR SELECT
USING (is_public = true OR auth.uid() = user_id);

CREATE POLICY "Users can insert their own records."
ON public.records FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own records."
ON public.records FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own records."
ON public.records FOR DELETE
USING (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- Community Posts table
-- -----------------------------------------------------------------------------
CREATE TABLE public.community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  caption TEXT,
  image_url TEXT,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL
);

-- -----------------------------------------------------------------------------
-- Set up Row Level Security (RLS) for community_posts table
-- -----------------------------------------------------------------------------
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "All users can view all posts."
ON public.community_posts FOR SELECT
USING (true);

CREATE POLICY "Users can insert their own posts."
ON public.community_posts FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own posts."
ON public.community_posts FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own posts."
ON public.community_posts FOR DELETE
USING (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- Supabase Storage for Avatars
-- -----------------------------------------------------------------------------

-- Create a public bucket for avatars
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for avatars bucket
-- Allow public read access to everyone
CREATE POLICY "Allow public read access on avatars" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');

-- Allow authenticated users to upload their own avatar
CREATE POLICY "Allow authenticated users to upload avatars" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated' AND (storage.foldername(name))[1] = auth.uid()::text);

-- Allow users to update their own avatar
CREATE POLICY "Allow users to update their own avatars" ON storage.objects FOR UPDATE USING (bucket_id = 'avatars' AND auth.uid() = owner);

-- Allow users to delete their own avatar
CREATE POLICY "Allow users to delete their own avatars" ON storage.objects FOR DELETE USING (bucket_id = 'avatars' AND auth.uid() = owner);

-- -----------------------------------------------------------------------------
-- Supabase Storage for Post Images
-- -----------------------------------------------------------------------------

-- Create a bucket for post images
INSERT INTO storage.buckets (id, name, public)
VALUES ('post_images', 'post_images', false)
ON CONFLICT (id) DO NOTHING;

-- Policies for post_images bucket
-- Allow all users to view images
CREATE POLICY "Allow all users to view images." ON storage.objects FOR SELECT USING (bucket_id = 'post_images');

-- Allow authenticated users to upload images
CREATE POLICY "Allow authenticated users to upload images." ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'post_images' AND auth.role() = 'authenticated');

-- Allow users to update their own images
CREATE POLICY "Allow users to update their own images." ON storage.objects FOR UPDATE USING (bucket_id = 'post_images' AND auth.uid() = owner);

-- Allow users to delete their own images
CREATE POLICY "Allow users to delete their own images." ON storage.objects FOR DELETE USING (bucket_id = 'post_images' AND auth.uid() = owner);

-- -----------------------------------------------------------------------------
-- Gamification: Badges and Rankings
-- -----------------------------------------------------------------------------

-- 뱃지 정보 테이블
CREATE TABLE IF NOT EXISTS public.badges (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    icon_type TEXT NOT NULL, -- Lucide 아이콘 명칭
    requirement_type TEXT NOT NULL, -- total_success, gym_count, level_reach 등
    requirement_value INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 유저가 획득한 뱃지 테이블
CREATE TABLE IF NOT EXISTS public.user_badges (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    badge_id UUID NOT NULL REFERENCES public.badges(id) ON DELETE CASCADE,
    earned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, badge_id)
);

-- RLS 설정
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "뱃지 정보는 누구나 조회 가능" ON public.badges FOR SELECT USING (true);
CREATE POLICY "자신의 뱃지 획득 정보만 조회 가능" ON public.user_badges FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "자신의 뱃지 정보 저장 가능" ON public.user_badges FOR INSERT WITH CHECK (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- Initial Data: Brands and Gyms
-- -----------------------------------------------------------------------------

-- 서울숲클라이밍 브랜드 및 지점 데이터 추가
DO $$
DECLARE
    v_brand_id uuid;
BEGIN
    -- 브랜드 추가 (또는 기존 브랜드 ID 가져오기)
    INSERT INTO public.brands (name, description)
    VALUES ('서울숲클라이밍', '서울 전역에 여러 지점을 운영하는 클라이밍 브랜드입니다.')
    ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description
    RETURNING id INTO v_brand_id;

    -- 지점 데이터 추가 (중복 방지)
    IF NOT EXISTS (SELECT 1 FROM public.gyms WHERE name = '서울숲클라이밍 뚝섬점') THEN
        INSERT INTO public.gyms (name, location, region, brand_id) VALUES ('서울숲클라이밍 뚝섬점', '서울 성동구 왕십리로10길 9-15', '서울', v_brand_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.gyms WHERE name = '서울숲클라이밍 잠실점') THEN
        INSERT INTO public.gyms (name, location, region, brand_id) VALUES ('서울숲클라이밍 잠실점', '서울 송파구 올림픽로 86 B1', '서울', v_brand_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.gyms WHERE name = '서울숲클라이밍 구로점') THEN
        INSERT INTO public.gyms (name, location, region, brand_id) VALUES ('서울숲클라이밍 구로점', '서울 구로구 디지털로31길 41 B1', '서울', v_brand_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.gyms WHERE name = '서울숲클라이밍 영등포점') THEN
        INSERT INTO public.gyms (name, location, region, brand_id) VALUES ('서울숲클라이밍 영등포점', '서울 영등포구 경인로 824 B1', '서울', v_brand_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.gyms WHERE name = '서울숲클라이밍 종로점') THEN
        INSERT INTO public.gyms (name, location, region, brand_id) VALUES ('서울숲클라이밍 종로점', '서울 종로구 율곡로 78 B1', '서울', v_brand_id);
    END IF;
END $$;
